# docker-composeのバージョン
version: '3'

services:
  # Webサーバ
  web:
    container_name: 'web-server'
    build: './docker/nginx/'
    # ホストの8080ポートとコンテナの80ポートをマッピング
    ports:
      - '80:80'
      - '443:443'
    # ホストの./srcディレクトリとコンテナの/var/www/htmlディレクトリを同期
    volumes:
      - './src:/var/www/html'
      - '/etc/letsencrypt:/etc/letsencrypt'
  # phpサーバ
  php:
    container_name: 'php-server'
    build: './docker/php/'
    # ホストの./srcディレクトリとコンテナの/var/www/htmlディレクトリを同期
    volumes:
      - './src:/var/www/html'

  # DBサーバ
  db:
    container_name: 'db-server'
    build: './docker/db/'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - './container/db/data:/var/lib/mysql'
